### PR TITLE
Instance changes

### PR DESCRIPTION
**Pull request by lukasepple**
Pull-Request introduces the following things:

* The fixed lazy `ByteString` instance & tests
* `Double` and `Float` instances
* A lazy `Text` instance
* An `Either` instance
* n-Tuple instances (Triples, Quadruples, Quintuples)
* container and unordered-container instances (`Map`s and `Set`s…)

### CODE REVIEW

**Comment by lukasepple** [comment]
Unsure why the build is failing, it compiles for me.

**Comment by lukasepple** [comment]
Since QuickCheck 2.8.2 there is a predefined instance for `Set` and `Map`. This breaks the nightly build here. Would be nice if we could check wether the instance is already defined using the preprocessor.

**Comment by skogsbaer** [comment]
With regard to compatibility with QuickCheck: cabal defines macros to check for a specific range of package versions, also see https://www.haskell.org/cabal/users-guide/developing-packages.html#conditional-compilation

You first need to add `{-# LANGUAGE CPP #-}` at the top of your source file. Then you can do conditional compilation like this (warning: I did not test it):

    #if MIN_VERSION_QuickCheck(2,8,2)
    -- code for QC 2.8.2 and newer
    #else
    -- code for older version of QC
    #endif

**Comment by skogsbaer** [comment]
Lukas, this is a great set of commits! Well done!

I'll merge the PR as soon as the CI problems are fixed. The only problem seems to be the instances for Map and Set defined in QC 2.8.2 and newer.

The next steps are: 

* more instances ;-)
* TemplateHaskell deriving function

**Pull request merged**
